if: "(type IN (pull_request, cron, api)) OR (tag IS present)"
language: node_js
node_js:
- stable
install:
- yarn
script:
- yarn start
deploy:
  provider: npm
  email: r.diener@wikom.de
  skip_cleanup: true
  api_key:
    secure: jApNJ/kH8ihV9b2fNN/CRkWF7oCWta2yGX79O4bTIxOfTRX0HGvqYDVCmTe4qNDSBSDjHk9AEZnGOpMhuxa0e+uJq2j9Bh71AnnsBtNiiAVxhiCXY96kkovgS5tG8bBLe6WNq+jXCJMNiDz7kdET1Qc3D6i0uL9urV57ZbB05RSjU1ByEB36KLldzay8GNbRO5XEMEqV9Kob1Uo5k2IFn2erKSdpEHCqXl0P5Ayfc1V2bxD2JmAUcGeentmsp5Rtlmvqbv3lXDMbeQHkh657OQ6PpC5VD+FmkUL5Mamm5JIu+ZxKqWnevj2qTXaOXhxPF+weIfP5MyAmZLcVyZt4j+jQuoDpLpsFvOqu6874DPHWWfI4nCeFO0vUtnJATVqNFgN85BsJS4oSAp7PCfote/coL28Xab4C6G0HV2lyGugtEgnV2AYFtHvk+83sAsYWTHwIiF5dLwfz80R+bgGPWPfMyfo9IvXfoaBr5dOiGBhu/4IUyvtNNK2/xGaH46i3Jo/iUE/UegntKZd807isYorxMvlQ4JLdbmnIxAiy/pOashBi3+lCwxTc8sKXi0RN1ZqCO93Zsrk8ZIiEcn62hD3Rb0zDgq1ukdKQeYQUG6BfPcUUUmNHGLloL6hnMrxlZD4d7be/Fg6vzyEPIKPTS1hRfwSOMMd7yEAl7ughiS4=
  on:
    tags: true
    all_branches: true
