if: "(type IN (pull_request, cron, api)) OR (tag IS present)"
language: node_js
node_js:
- stable
install:
- yarn
script:
- yarn start
deploy:
  provider: npm
  email: r.diener@wikom.de
  skip_cleanup: true
  api_key:
    secure: iVjFoB0ueIdUELkh7k79zDkOEoEpP4yvj/IY/RdgHiSENEnzO/gKGPAHGPc2YZIylLWeHUbtsZSDCZW9T+ZUG3Hdiz35GPjGbYtxP+R5JSoQSStMLBjOKq+kCEvk6HzAzqNKI0lfCi7jOAaBr64gwGS3rIRWAnEpjrOxLH8aoUDhXKYpe8oY2jIo9Yyabc/e5RIY6GQtd+9oKxqKOd4YXdt0qgoc4JknQrn/Vosgbf3nwJLun7OEoLwaKZqoaXeIlYj0gACN/sab1tj8Lg8QkYrQ6e75EajTavgHK0C8Ph30x0QCY2kH1myiJjTxIL4tMzhrp6hfNfPwydrn/wW7npUVosbewTsxIZByZgBtAqy8yKbk2WOOhPq1Thru1QAPZTPZRoHDQ0wy016GERpwU+mY0XX6mJ4RKwbljP7xSgy6tLlccwQFLRsS/o1GRelZwe2Nqk+4gFLV8L/4+cwIEKE2Ay72IclWe5y7wH+mA8VvKXiixDWeaLUJTY+azLccGlNIXimdcAmR3/nX5NyDU4ycXnHgkJ8cq3IM5eit7+vuuog+az/26wX67tSDSh3wVsqVW1jbtazNR/xtf+2Ke8+Y6RJCFC5mkFs9VQgVlQ8cMWTIkzLsnGBB3VuduUz0Vcrly1DUp8uxlIpnSIs0wQQqJzJMZT86/TAYMp60dA8=
  on:
    tags: true
    all_branches: true
