if: "(type IN (pull_request, cron, api)) OR (tag IS present)"
language: node_js
node_js:
- stable
install:
- yarn
script:
- yarn start
deploy:
  provider: npm
  email: r.diener@wikom.de
  skip_cleanup: true
  api_key:
    secure: HoQPTK+ExKRx59CdBqfEdsSyIgaUhQag1l9990+bvPSh5CoW+lpVy6UFftdB/wSRnqUZMrljuR/W4iRfUKhQTWdQhGRAq942iXghx2i5LP3xskY8ofGKkQHdyzdBZCgZesvtsWxp9edrz4HnfoZCe+VoWT53Cylyzp08/2+9d6hyT1ixVx3Q7jPf7bWVaE2v4ENuHZwI7iVSGolck9rPR0nFLOr+QOVNWKJFLqVVpo6VyMEwbvzM7I39DV/pEzkYW9JNADXt0Rmcm1b6UpTc6IP2ea1lT1/jCWZG/0t4QOazLw3kiTIRjRhYDqI4oTQ8eezWWZarc8rQJxvqNFDzxLbjTqIiyyRbFdE942TJ2cQSoqfcTi/0qQynFAE2Bc3NwM8rbyV3Noy+tLndUX1MOU/oiFRRa0gJMn7g55qVxfqpUPxRcJnyz6BRg33xal+f74f2EgTnmmJMdfAvfQOQV5T602gknuqkSK8o+WBdctngocpHWhTnrfAPwhzUALk4a2sev73o5XHbnZ/1MwixLJGmM+i01msXjiuFcEZVnYzYe93Z9pXha2PDa2DTkS1kpz2hCGcSmWLnaMhh5dTKCM+yeaqhVvuZernDrp8+Pl0xZ7NxCvZPYqdLdGdMrm2kgpkYJHcryEyW7bWDjNVdAa3Du3JH9nCZIzzWQIdVp3k=
  on:
    tags: true
    all_branches: true
